### ISSUE TITLE
Are you active on Discord?

### ISSUE THREAD

**Issue by bjsi** [howardwarren1982/nationality_predictor#1]
There's a community of RemNote users and plugin developers [here on Discord](https://bit.ly/RemNoteDiscord). We just approved your plugin and made it available in the plugin marketplace :100:. If you join and send me your username, you will be able to post in the plugin updates channel to announce the release of your plugin :).

Good work!

**Comment by howardwarren1982** [comment]
Hello, Yea im on been busy as of late, but will try to keep up to date
